auto: true

markdown: rdiscount

highlighter: 'rouge'
#paginate: 8
permalink: /:title

name: “Linjie's Blog”
title: Linjie's blog
description: Everything about Linjie.
url: http://jounywang.github.io
feed: /atom.xml
author_info: <a href="http://jounywang.github.io/">Linjie</a>

